export const ExampleEvents = [
  {
    id: 1,
    name: "Writing Workshop",
    date: "14-01-2024",
    startTime: "9:00 AM",
    image: "rainforest.jpg",
    location: "Chandmari House",
    endTime: "12:00 AM",
    description: "Learn to write better",
  },
  {
    id: 2,
    name: "Web Development Workshop",
    image: "rainforest.jpg",
    date: "14-01-2024",
    startTime: "9:00 AM",
    location: "Chandmari House",
    endTime: "12:00 AM",
    description: "Build your own website",
  },
  {
    id: 3,
    name: "Excell 101",
    date: "14-01-2024",
    startTime: "9:00 AM",
    image: "rainforest.jpg",
    location: "Chandmari House",
    endTime: "12:00 AM",
    description: "Excell like a boss",
  },
  {
    id: 4,
    name: "Poetry 101",
    date: "14-01-2024",
    startTime: "9:00 AM",
    image: "rainforest.jpg",
    endTime: "12:00 AM",
    location: "Chandmari House",
    description: "Poetry like a boss",
  },
  {
    id: 5,
    name: "Cars 101",
    date: "14-01-2024",
    startTime: "9:00 AM",
    endTime: "12:00 AM",
    image: "rainforest.jpg",
    location: "Chandmari House",
    description: "Learn about the inner workings of a car.",
  },
  {
    id: 6,
    name: "Godzilla",
    date: "14-01-2024",
    startTime: "9:00 AM",
    image: "rainforest.jpg",
    location: "Chandmari House",
    endTime: "12:00 AM",
    description: "Say hi to godzilla.",
  },
];
